feat: Add VTEX RequestCapture analytics
vtex-sites/base.store pull request #116
Opened 2021-11-24 15:31 UTC by igorbrasileiro

## What's the purpose of this pull request?
This pull request adds the Request Capture engine to the analytics backend.

## How it works? 
<em>Tell us the role of the new feature, or component, in its context.</em>

## How to test it?
<em>Describe the steps with bullet points. Is there any external reference, link, or example?</em> 

## References
<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>  

<em>Extra tip: add references to related issues or mention people important to this PR may be good for the documentation and reviewing process</em>

2021-11-24 17:28 UTC, icazevedo commented on src/sdk/analytics/utils/navigation.ts
> +  expirationDate.setTime(expirationDate.getTime() + expirationTime)
I think this is more readable

```suggestion
  expirationDate.setTime(new Date().getTime() + expirationTime)
```

2021-11-25 12:56 UTC, igorbrasileiro commented on src/sdk/analytics/utils/navigation.ts
> +  expirationDate.setTime(expirationDate.getTime() + expirationTime)
Fixed

2021-11-29 14:06 UTC, lariciamota requested changes

2021-11-29 14:06 UTC, lariciamota commented on src/sdk/analytics/utils/navigation.ts
> +  return uuid
To stop SonarQube warning:
```suggestion
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0

    return (c === 'x' ? r : (r & 0x3) | 0x8).toString(16)
  })
```

2021-11-29 14:42 UTC, lariciamota requested changes

2021-11-29 14:42 UTC, lariciamota commented on src/sdk/analytics/utils/navigation.ts
> + * Get account name from the environment varibable GATSBY_STORE_ID.
```suggestion
 * Get account name from the environment variable GATSBY_STORE_ID.
```

2021-12-29 19:25 UTC, closed without merging