feat: Style the PDP
vtex-sites/base.store pull request #200
Opened 2022-01-04 13:59 UTC by filipewl

## What's the purpose of this pull request?

Prepare the styles for the PDP according to the design in [this Figma file](https://www.figma.com/file/wS0Kek1aSzIRl20jdtnSsL/Closed-Beta-Version?node-id=1%3A5839). 

Note that for this task, we're only concerned with styling the inner region of the page: from after the breadcrumb to the "You might also like" section. Areas such as the navigation bar or the footer have their own tasks. Some other inner components, such as the quantity and SKU selectors, are also already styled. So perhaps the main objective of this task is to glue together these components (e..g product title, image gallery, quantity & SKU selector, and product description) and address the remaining styles.

This PR requires the changes from #191. Styles for the "You might also like" section are in there, as well as the new `ProductShelf` component, so I won't re-do them here. Once #191 is merged, we should also merge its changes here, uncomment the notes, and, ideally, it should all work automatically.

Mobile|Desktop
-|-
![image](https://user-images.githubusercontent.com/381395/148067141-27ccac6f-b783-4f1b-a23e-b406affd720f.png)|![image](https://user-images.githubusercontent.com/381395/148066983-c9b1a257-0443-4be9-876f-70b5866d860e.png)

## How it works? 
<em>Tell us the role of the new feature, or component, in its context.</em>

## How to test it?
Visit the preview link.

## References

- Similar to #191, but for the PDP.
- Jira issue [FSSS-79 Style PDP](https://vtex-dev.atlassian.net/jira/software/projects/FSSS/boards/632?selectedIssue=FSSS-79).
- Jira issue [FSSS-78 Style Product Title](https://vtex-dev.atlassian.net/jira/software/projects/FSSS/boards/632?selectedIssue=FSSS-78).

2022-01-05 23:57 UTC, hellofanny commented on src/components/sections/ProductDetails/ProductDetails.tsx
> +        <section className="product-details__title">
Maybe we can use `<header>` here

2022-01-05 23:59 UTC, hellofanny commented on src/components/sections/ProductDetails/ProductDetails.tsx
> +            <div className="prices">
I think you can use our `Price` component here! See an example on `ProductCard` component.

2022-01-06 00:01 UTC, hellofanny commented on src/components/sections/ProductDetails/product-details.scss
> +  .price__old {
If you replace for our `Price` component, you won't need that :)

2022-01-06 00:04 UTC, hellofanny commented on src/components/ui/ProductTitle/ProductTitle.tsx
> +        <div className="product-title__footer / text-body-small">
Are we having other elements here? If not, I think we can just call it `product-title__addendum`. What do you think?

2022-01-06 00:05 UTC, hellofanny commented on src/components/ui/ProductTitle/product-title.scss
> +@import "../../../styles/utilities.scss";
```suggestion
@import "../../../styles/scaffold";
```

2022-01-06 00:05 UTC, hellofanny commented on src/components/ui/ProductTitle/product-title.scss
> +@import "../../../styles/utilities.scss";
You can use this style instead :)

2022-01-06 00:11 UTC, hellofanny requested changes
Awnnn Looks amazing!! 😍 😍 😍 

I've left a few comments! Please take a look into!

2022-01-06 00:11 UTC, eduardoformiga approved these changes
Awesome Job! 👏 ✨

2022-01-06 00:11 UTC, eduardoformiga commented on src/components/sections/ProductDetails/product-details.scss
> +  width: calc(100% + var(--page-padding-phone) + var(--page-padding-phone));
Nice trick!

```suggestion
  width: calc(100% + (2 * var(--page-padding-phone)));
```

2022-01-06 01:11 UTC, hellofanny commented on src/components/sections/ProductDetails/ProductDetails.tsx
> +            refNumber="Ref.: 54412"
That's a nice question! Actually, here we can also pass a react node instead of string 🤔

2022-01-06 21:38 UTC, merged