chore: Styles and Integrates Image Gallery
vtex-sites/base.store pull request #409
Opened 2022-03-22 14:50 UTC by danzanzini

## What's the purpose of this pull request?

This PR addresses the tasks of [Style](https://vtex-dev.atlassian.net/browse/FSSS-58) and [Integrate](https://vtex-dev.atlassian.net/browse/FSSS-55) the [ImageGallery Component](https://github.com/vtex-sites/base.store/blob/master/src/components/ui/ImageGallery/ImageGallery.tsx) to the Product Display Page, as shown in this [figma file](https://www.figma.com/file/zHMOtOPduiM0hNNcg21iR1/Handoff-PDP-v0.1?node-id=18%3A33225).

There are still some minor adjustments to make. I've added them to the checklist below and I may tackle it in this PR or in future PRs so we can merge this one.

## How does it work?

I've changed the ImageGallery to not use the [Faststore's useSlider](https://github.com/vtex/faststore/blob/master/packages/ui/src/hooks/useSlider/useSlider.ts) component in favor of an approach using the default browser scroll, with a button controlling it through javascript.

The results are as follows:
|State |Desktop  | Mobile|
--- | --- | ---|
|1 item|![image](https://user-images.githubusercontent.com/8497187/162503014-76ce221a-820c-4903-96d1-0d419d831fc4.png)|![image](https://user-images.githubusercontent.com/8497187/162502952-7d6697c7-415a-499f-92b0-63bb3572a79f.png)|
|> 1 item|![image](https://user-images.githubusercontent.com/8497187/162503249-6f1ccf14-befb-4634-b4b7-3b2b7a93c6d7.png)|![image](https://user-images.githubusercontent.com/8497187/162503315-7f472fd8-9b02-45fb-b552-9d3cea17a034.png)|
|with scroll|![image](https://user-images.githubusercontent.com/8497187/162508181-7239cb32-8522-43e0-a02d-0553feed4cf3.png)|![image](https://user-images.githubusercontent.com/8497187/16250
|gif|![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/8497187/162510633-5659d2d3-07fb-4e74-9e49-4407519674f1.gif)|![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/8497187/162510404-a6484274-fe06-4d71-b230-e1da83d64a85.gif)|

## How to test it?

Go to the preview link and test the PDP of products with different amounts of product images:
- [with only 1 image](https://preview-409--base.preview.vtex.app/aedle-vk1-headphone-99988211/p)
- [with more than 1 image, but without scroll](https://preview-409--base.preview.vtex.app/awesome-plastic-bacon-9938908/p)
- [with scroll](https://preview-409--base.preview.vtex.app/awesome-wooden-bike-sleek-47501742/p)

Remember to test it for desktop and mobile. Try around with the scroll, use it with the buttons or with the scroll bar.

## Checklist

<em>You may erase this after checking them all ;)</em>

- [x] CHANGELOG entry added
- [x] Remove padding of selector items when there is no scroll [Jira task created](https://vtex-dev.atlassian.net/browse/FSSS-280)
- [x] Display/hide arrow buttons according to scroll position [Jira task created](https://vtex-dev.atlassian.net/browse/FSSS-280)
- [x] Uses aspect ratio instead of fixed height to define max height of main image
- [x] Adding Zoom tool [Jira task created](https://vtex-dev.atlassian.net/browse/FSSS-281)
- [x] Themify component [Jira task created](https://vtex-dev.atlassian.net/browse/FSSS-282)

Thanks to @renatamottam @saranicoly @heitorado @filipeafns and @lucasfp13 for all the help

2022-04-20 17:48 UTC, filipeafns requested changes
Hey @danzanzini. This is a great work, congratulations 🎉 

I Have a single issue I found while testing this on both Chrome and Safari, Desktop and Mobile:

- I know this is similar to the design I did, but I think we should decrease the overlap between the buttons with the first and last button within the scroll area (check attachment 1) `data-fs-image-gallery-selector-elements`.

![attachement 1](https://user-images.githubusercontent.com/29554881/164291313-54ed0662-615c-4a57-a93c-2cea6ee1d72c.png)

- Maybe this will solve the other the issue with the last thumb, that's hidden behind the button (check attachment 2)
![attachement 2](https://user-images.githubusercontent.com/29554881/164291320-f1a42214-eea3-44cb-bd1e-d578c2ece185.png)

2022-04-20 19:24 UTC, renatamottam approved these changes
Amazing job, @danzanzini 👏 👏 👏

2022-04-22 13:55 UTC, filipewl commented on CHANGELOG.md
> +- Refactors ImageGallery component to not use the useSlider component (#409)
Can you move these new entries to the beginning of their sections? [The latest version comes first.](https://keepachangelog.com/en/1.0.0/#:~:text=The%20latest%20version%20comes%20first.).

2022-04-22 14:10 UTC, saranicoly approved these changes
LGTM. Great work!

2022-04-22 14:38 UTC, filipewl commented on src/components/ui/ImageGallery/ImageGallerySelector.tsx
> +              <Image
Is there a way to use responsive images here? LH complained about not using them.

![CleanShot 2022-04-22 at 11 35 10](https://user-images.githubusercontent.com/381395/164736426-578d2937-74ef-49d4-93f9-7836cd68bc4b.png)

![CleanShot 2022-04-22 at 11 35 29](https://user-images.githubusercontent.com/381395/164736477-d806454b-7970-4c23-b5b9-48563c913718.png)

You can check the report here https://googlechrome.github.io/lighthouse/viewer/ by pasting the JSON file inside [here](https://github.com/vtex-sites/base.store/files/8541838/sfj-443454d--base.preview.vtex.app_2022-04-22_11-27-59.json.zip).

2022-04-22 14:56 UTC, filipewl reviewed
Great job @danzanzini (and @renatamottam?)!!!

I found a Lighthouse issue in the PDP version with the gallery & scroll. What do you think of updating the PDP's URL for LH and tests (in [store.config.js](https://github.com/vtex-sites/base.store/commit/443454d2077e9f1cbf9816c2c5c62b57d94e67bf)) to use that version to account for a more "complete" PDP version?

2022-04-22 14:56 UTC, filipewl commented on src/components/ui/ImageGallery/ImageGallerySelector.tsx
> +              aria-label={`Load ${image.alternateName} - Image ${idx + 1} of ${
Do we really need to mention "load"?
```suggestion
              aria-label={`${image.alternateName} - Image ${idx + 1} of ${
```

2022-04-26 17:06 UTC, filipewl commented
Closed in favor of https://github.com/vtex-sites/gatsby.store/pull/6.

2022-04-26 17:06 UTC, closed without merging