Feat: Hero Theming
vtex-sites/base.store pull request #435
Opened 2022-03-30 22:57 UTC by renatamottam

## What's the purpose of this pull request?
This PR applies the new Theming structure #407 to `Hero`: new scoped tokens linked to global ones.

## How does it work?
This PR uses local variables to parameterize the `Hero` properties, then connects these scoped tokens to the global ones.

||Before|After|
|-|-|-|
|Mobile|<img width="320" alt="image" src="https://user-images.githubusercontent.com/11613011/160944324-6810e624-6e50-4025-b556-7eaf9cb7c62e.png">|<img width="320" alt="image" src="https://user-images.githubusercontent.com/11613011/160944305-427fbe23-de0e-43de-b196-e02305d15137.png">|
|Desktop|<img width="1380" alt="image" src="https://user-images.githubusercontent.com/11613011/160941363-2b1fb843-ffaf-4540-8753-14b2b7344c70.png">|<img width="1380" alt="image" src="https://user-images.githubusercontent.com/11613011/160943937-37ba7f23-7378-4d88-a0a7-2520758e4b71.png">|

||Before|After|
|-|-|-|
|Mobile|<img width="320" alt="image" src="https://user-images.githubusercontent.com/11613011/160944240-81195a6f-e0a5-4dc6-b3b2-25650a182b4f.png">|<img width="320" alt="image" src="https://user-images.githubusercontent.com/11613011/160944200-4d022183-6aa2-44f4-a102-29cf9ed1c0a2.png">|
|Desktop|<img width="1380" alt="image" src="https://user-images.githubusercontent.com/11613011/160941733-aee6f7c7-0694-4ab2-945c-5c6a81abba7a.png">|<img width="1380" alt="image" src="https://user-images.githubusercontent.com/11613011/160944128-be82fe17-628f-42f8-8b4d-4aebbc53fff7.png">|

### New global tokens
None.

### New local tokens for `Hero`
|Local token|Default value / global token linked|
|-|-|
| `--fs-hero-bkg-color` | `var(--fs-color-primary-bkg)`|
| `--fs-hero-text-color` | `var(--fs-color-text-inverse)`|
| `--fs-hero-text-title-color` | `var(--fs-hero-text-color)`|
| `--fs-hero-text-title-size` | `var(--fs-text-size-7)`|
| `--fs-hero-text-title-small-size` | `var(--fs-text-size-6)`|
| `--fs-hero-text-title-line` | `1.1`|
| `--fs-hero-text-paragraph-color` | `var(--fs-hero-text-color)`|
| `--fs-hero-text-paragraph-size` | `var(--fs-text-size-lead)`|
| `--fs-hero-text-paragraph-line` | `1.33`|

## How to test it?
The `Hero` component should look very similar as it was before this effort.

## Checklist
- [ ] CHANGELOG entry added

2022-03-31 16:17 UTC, sergiofontes commented
Great work, miga!

I'm wondering, though, if—for the sake of conciseness and to ease the tokens' findability through the browser's Inspect—it's worth shrinking a little bit these local tokens.

For instance: 
*  ~`--fs-hero-text-title-size`~ could be `--fs-hero-title-size`;
* and ~`--fs-hero-text-paragraph-size`~ could simply be `--fs-hero-text-size`.

What do you think?

2022-03-31 17:58 UTC, sergiofontes requested changes

2022-03-31 17:58 UTC, sergiofontes commented on src/components/ui/Hero/hero.scss
> +  --fs-hero-title-small-size   : var(--fs-text-size-6);
`-small` should be placed at the end: `--fs-hero-title-size-small`

2022-04-01 01:23 UTC, hellofanny approved these changes
Great work, miga! 
I'm not sure about the type variants renaming `type Variant = 'primary' | 'secondary'` because it's not very clear what does it mean, but fill the purpose and I don't have any better suggestion 🙈

2022-04-01 18:27 UTC, eduardoformiga reviewed
LGTM! 👏 
I notice some visual differences compared with the mobile/desktop versions from the https://base.vtex.app/ in both variations. Was that intentional?

2022-04-06 20:29 UTC, eduardoformiga approved these changes

2022-04-07 22:39 UTC, saranicoly approved these changes
LGTM!

2022-04-12 13:39 UTC, ArthurTriis1 approved these changes

2022-04-14 14:54 UTC, lucasfp13 approved these changes

2022-04-14 17:33 UTC, merged