feat: Add view-item event
vtex-sites/base.store pull request #78
Opened 2021-10-14 14:16 UTC by ArthurTriis1

Signed-off-by: Arthur Andrade <arthurfelandrade@gmail.com>

## What's the purpose of this pull request?
This PR add trigger for view-item analytics event, according to GA4.

## How it works? 
For this, when an item is clicked the PR add in `window.dataLayer` one more event, with name and properties according to GA4.

## How to test it?
This PR also add cypress tests for this event, testing if the event is added to dataLayer and if the properties has been added too.

## References
[GA4](https://developers.google.com/analytics/devguides/collection/ga4/reference/events#view_item)

2021-10-18 12:52 UTC, tlgimenes requested changes

2021-10-18 19:26 UTC, igorbrasileiro requested changes
Great job, @ArthurTriis1!
Left some comments

2021-10-19 18:29 UTC, igorbrasileiro approved these changes

2021-10-20 13:35 UTC, tlgimenes requested changes

2021-10-21 13:48 UTC, tlgimenes approved these changes
LGTM, I really liked how it ended up 🎉

2021-10-21 14:35 UTC, merged